### ISSUE TITLE
클래스 안에 클래스의 변환도 가능할까요?

### ISSUE THREAD

**Issue by juniqlim** [shirohoo/full-text-mapper#12]
안녕하세요. 
혹시 클래스 안에 클래스의 변환도 가능할까요?
```
class Data {
SubData subData;
}
class SubData {
String content;
}
```
이런식의 구성도 전문으로 변환이 가능할까요?

**Comment by shirohoo** [comment]
아니요 아직 그런 기능은 없습니다 😭

**Comment by shirohoo** [comment]
![image](https://user-images.githubusercontent.com/71188307/153355036-e7c27a6e-c771-40f5-bd82-75a9b5f47eb7.png)
